---
title: "ggasym"
author: "Joshua H. Cook"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ggasym}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, warning=FALSE, message=FALSE}
library(tibble)
library(ggplot2)
library(ggasym)
```

Below is a simple example of how this package can be used.

```{r}
tib <- tibble(g1 = c("A", "A", "B"),
              g2 = c("B", "C", "C"),
              val_1 = c(1, 2, 3),
              val_2 = c(-1, 0, 1))
tib
```

```{r}
ggplot(tib) +
    geom_asymmat(aes(x = g1, y = g2, fill_tl = val_1, fill_br = val_2)) +
    scale_fill_br_gradient(low = "lightblue1", high = "dodgerblue") +
    scale_fill_tl_gradient(low = "lightpink", high = "tomato") +
    labs(fill_tl =  "top-left fill", fill_br = "bottom-right fill")
```

The following are tests of unintended uses of the `geom`. Right now, they will not fail and throw an error, but I want a default fill to be used, instead. I need to figure out how they do that in ggplot2.

```{r}
ggplot(tib) +
    geom_asymmat(aes(x = g1, y = g2, fill_tl = val_1, fill_br = val_2))

ggplot(tib) +
    geom_tile(aes(x = g1, y = g2), fill = "grey20")

```

