---
title: "Testing"
author: "Joshua H. Cook"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(tidyverse)
# library(ggasym)
library(scales)
```



## Experimenting with the current build



### TODO

*The following code chunk works!*

```{r}
j <- ggplot(mpg) +
    geom_asymmat(aes(x = manufacturer, y = class,
                     fill_tl = cty, fill_br = hwy)) +
    scale_fill_tl_gradient(low = "green", high = "red") +
    scale_fill_br_gradient(low = "blue", high = "orange")
j_build <- ggplot_build(j)
as_tibble(j_build$data[[1]])
as_tibble(j_build$data[[2]])
```

```{r}
k <- ggplot(mpg) +
    geom_tile(aes(x = manufacturer, y = class, fill = cty)) +
    scale_fill_gradient(low = "green", high = "red")
k_build <- ggplot_build(k)
as_tibble(k_build$data[[1]])
```

```{r}
library(ggnewscale)
# Equivalent to melt(volcano)
topography <- expand.grid(x = 1:nrow(volcano),
                          y = 1:ncol(volcano))
topography$z <- c(volcano)

# point measurements of something at a few locations
set.seed(42)
measurements <- data.frame(x = runif(30, 1, 80),
                           y = runif(30, 1, 60),
                           thing = rnorm(30))

g1 <- ggplot(mapping = aes(x, y)) +
    geom_contour(data = topography, aes(z = z, color = stat(level))) +
    scale_color_gradient(low = "green", high = "red")

g2 <- ggplot(mapping = aes(x, y)) +
    geom_contour(data = topography, aes(z = z, color = stat(level))) +
    scale_color_gradient(low = "green", high = "red") +
    new_scale_color()

g3 <- ggplot(mapping = aes(x, y)) +
    geom_contour(data = topography, aes(z = z, color = stat(level))) +
    scale_color_gradient(low = "green", high = "red") +
    new_scale_color() +
    geom_point(data = measurements, size = 3, aes(color = thing)) +
    scale_color_gradient(low = "blue", high = "orange") +
    labs(colour = "colour_number_1", colour_new = "colour_number_2")

g3_build <- ggplot_build(g3)
as_tibble(g3_build$data[[1]])
as_tibble(g3_build$data[[2]])
```

## Basic Example

```{r}
tib <- tibble(g1 = c("A", "A", "B"),
              g2 = c("B", "C", "C"),
              val_1 = c(1, 2, 3),
              val_2 = c(-1, 0, 1))
tib
ggplot(tib) +
    geom_asymmat(aes(x = g1, y = g2, fill_tl = val_1, fill_br = val_2)) +
    scale_fill_br_gradient(low = "lightblue1", high = "dodgerblue") +
    scale_fill_tl_gradient(low = "lightpink", high = "tomato")


# the function fails if no scale is passed --> how to assign a default scale?
# (perhaps, in setup_data()?)
ggplot(tib) +
    geom_asymmat(aes(x = g1, y = g2, fill_tl = val_1, fill_br = val_2))
```

